In [1]:
import numpy as np
import pandas as pd

In [2]:
user_data={
    "marksA": np.random.randint(1,100,10),
    "marksB": np.random.randint(1,100,10),
    "marksC": np.random.randint(1,100,10),
}


In [3]:
df=pd.DataFrame(user_data)
print(df)

   marksA  marksB  marksC
0      60      40      30
1      50      53      26
2      56      75      71
3      36       4      60
4      44      96      75
5      44      77      67
6      63      47      14
7      80      96      83
8      76      87       6
9      87      72      43


In [4]:
df.to_csv('marks.csv')

In [9]:
df1=pd.read_csv('marks.csv')
df1=df1.drop(columns=['Unnamed: 0'])
print(df1)

   marksA  marksB  marksC
0      60      40      30
1      50      53      26
2      56      75      71
3      36       4      60
4      44      96      75
5      44      77      67
6      63      47      14
7      80      96      83
8      76      87       6
9      87      72      43


In [10]:
df1.describe()

marksA     marksB     marksC
count  10.000000  10.000000  10.000000
mean   59.600000  64.700000  47.500000
std    16.984961  28.890791  27.362789
min    36.000000   4.000000   6.000000
25%    45.500000  48.500000  27.000000
50%    58.000000  73.500000  51.500000
75%    72.750000  84.500000  70.000000
max    87.000000  96.000000  83.000000

In [11]:
df1.head(n=3)

marksA  marksB  marksC
0      60      40      30
1      50      53      26
2      56      75      71

In [12]:
df1.tail(n=3)

marksA  marksB  marksC
7      80      96      83
8      76      87       6
9      87      72      43

In [13]:
df1.iloc[3]

marksA    36
marksB     4
marksC    60
Name: 3, dtype: int64

In [14]:
df1.iloc[3,2]

60

In [19]:
idx=df1.columns.get_loc('marksC')
print(df1.iloc[:,idx])

0    30
1    26
2    71
3    60
4    75
5    67
6    14
7    83
8     6
9    43
Name: marksC, dtype: int64


In [21]:
idx=[df1.columns.get_loc('marksA'),df1.columns.get_loc('marksC')]
print(df1.iloc[:5,idx])

   marksA  marksC
0      60      30
1      50      26
2      56      71
3      36      60
4      44      75


In [22]:
print(df1)

   marksA  marksB  marksC
0      60      40      30
1      50      53      26
2      56      75      71
3      36       4      60
4      44      96      75
5      44      77      67
6      63      47      14
7      80      96      83
8      76      87       6
9      87      72      43


In [27]:
df1=df1.sort_values(by=['marksA','marksC'],ascending=False)
print(df1)

   marksA  marksB  marksC
9      87      72      43
7      80      96      83
8      76      87       6
6      63      47      14
0      60      40      30
2      56      75      71
1      50      53      26
4      44      96      75
5      44      77      67
3      36       4      60


In [30]:
data_array=df1.values
print(data_array,data_array.shape,type(data_array))

[[87 72 43]
 [80 96 83]
 [76 87  6]
 [63 47 14]
 [60 40 30]
 [56 75 71]
 [50 53 26]
 [44 96 75]
 [44 77 67]
 [36  4 60]] (10, 3) <class 'numpy.ndarray'>


In [34]:
df2=pd.DataFrame(data_array,dtype='int32',columns=['physics','chemistry','maths'])
df2.to_csv('pcm.csv',index=False)