In [1]:
import numpy as np

In [16]:
a=np.array([1,2,3,4,5],dtype=np.float64)
print(a,type(a))
print(a.shape)

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>
(5,)


In [18]:
a=np.zeros((3,3))
print(a)
a=np.ones((3,3),dtype=np.int64)
print(a)
a=np.full((2,3),9)
print(a)
a=np.eye(4)
print(a)
a=np.random.random((3,3))
print(a)
print(a[1,:])
a[1:3,1]=0
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[9 9 9]
 [9 9 9]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.78906939 0.27005125 0.16042827]
 [0.31916558 0.65786    0.22866933]
 [0.73452792 0.4526204  0.80390053]]
[0.31916558 0.65786    0.22866933]
[[0.78906939 0.27005125 0.16042827]
 [0.31916558 0.         0.22866933]
 [0.73452792 0.         0.80390053]]


In [20]:
a=np.random.random((3,3))
b=np.random.random((3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b)) #element wise
print(np.sqrt(a,b))
print(np.dot(a,b)) #matrix multiplication

[[1.15874209 1.553142   0.98164033]
 [1.02721473 1.23566072 0.96911371]
 [0.8783184  0.95063069 1.15788222]]
[[ 0.83667628 -0.13614661 -0.14820794]
 [-0.69416783  0.51760118  0.65999569]
 [-0.1956652  -0.47681745  0.55460077]]
[[6.19568525 0.8388119  0.73764984]
 [0.1934764  2.44166646 5.27018578]
 [0.63562721 0.33193027 2.83861369]]
[[0.16066401 0.59842855 0.23541304]
 [0.14332528 0.31473661 0.12589677]
 [0.18328959 0.16908596 0.2582773 ]]
[[0.99885394 0.84172305 0.64553559]
 [0.40807285 0.93628572 0.90252684]
 [0.58423163 0.48673054 0.92533318]]
[[1.5291432  1.7059796  1.6690963 ]
 [0.99995052 1.35741232 1.65241427]
 [0.93785394 0.92587364 1.22646171]]


In [25]:
a=np.array([1,2,3,4,5])
print(np.sum(a))
a=np.ones((3,2))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))


15
[3. 3.]
[2. 2. 2.]


In [67]:
a=np.random.random((5,4))
a.resize((10,2))
print(a)

[[0.12632952 0.13507916]
 [0.50566217 0.02152481]
 [0.94797021 0.82711547]
 [0.01501898 0.17619626]
 [0.33206357 0.13099684]
 [0.80949069 0.34473665]
 [0.94010748 0.58201418]
 [0.87883198 0.84473445]
 [0.90539232 0.45988027]
 [0.54634682 0.79860359]]


In [51]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[2 9 6 4 0 3 1 7 8 5]


In [40]:
a=np.random.random((2,3))
print(a)
a=np.random.rand(2,3)
print(a)
a=np.random.randint(1,10,(5,6))
print(a)
a=np.random.randn(2,3)
print(a)


[[0.5124334  0.41617757 0.82782288]
 [0.97067424 0.89680983 0.87233946]]
[[0.6724858  0.77304723 0.14109972]
 [0.17372171 0.32349446 0.735333  ]]
[[8 2 5 9 3 6]
 [6 4 8 9 8 7]
 [1 4 4 1 3 5]
 [7 2 5 5 9 6]
 [4 1 3 5 4 1]]
[[-2.75187906  0.38318159 -1.29825209]
 [ 0.81595026 -0.19797413 -1.75893935]]


In [57]:
a=np.random.randint(1,10,(5,6))
print(a)
print(np.min(a,axis=0))
print(np.min(a,axis=1))

print(np.mean(a,axis=0))

print(np.median(a,axis=0))

[[8 9 6 8 1 4]
 [2 5 5 7 9 9]
 [3 8 6 6 5 6]
 [9 6 9 2 2 9]
 [8 1 4 5 3 1]]
[2 1 4 2 1 1]
[1 2 3 2 1]
[6.  5.8 6.  5.6 4.  5.8]
[8. 6. 6. 6. 3. 6.]


In [59]:
wts=np.array([1,2,3,4,5])
print(np.average(a,weights=wts,axis=0))

[6.46666667 4.8        6.         4.86666667 3.8        5.4       ]


In [60]:
print(np.std(a,axis=0))

[2.89827535 2.78567766 1.67332005 2.05912603 2.82842712 3.05941171]


In [62]:
print(np.var(a,axis=0))

[8.4  7.76 2.8  4.24 8.   9.36]


In [69]:
print(a)
print(a.T)

[[0.12632952 0.13507916]
 [0.50566217 0.02152481]
 [0.94797021 0.82711547]
 [0.01501898 0.17619626]
 [0.33206357 0.13099684]
 [0.80949069 0.34473665]
 [0.94010748 0.58201418]
 [0.87883198 0.84473445]
 [0.90539232 0.45988027]
 [0.54634682 0.79860359]]
[[0.12632952 0.50566217 0.94797021 0.01501898 0.33206357 0.80949069
  0.94010748 0.87883198 0.90539232 0.54634682]
 [0.13507916 0.02152481 0.82711547 0.17619626 0.13099684 0.34473665
  0.58201418 0.84473445 0.45988027 0.79860359]]
